In [2]:
import pandas as pd

# Load Landsat data
landsat_data = pd.read_csv('prf_I5_2000_9_norm_landsat8.csv')

# Load LiDAR data
lidar_data = pd.read_csv('tvol_lidarP.csv')

# Display the first few rows of the datasets
print("Landsat Data Preview:")
display(landsat_data.head())
print("LiDAR Data Preview:")
display(lidar_data.head())

Landsat Data Preview:

,area,age,site_index,band1_mean,band2_mean,band3_mean,band4_mean,band5_mean,band7_mean,Target
0,0.099653,0.387879,0.322036,0.015679,0.007154,0.023679,0.204062,0.042123,0.029575,433.49060
1,0.062917,0.218182,0.224337,0.020886,0.013045,0.036076,0.140909,0.175420,0.106167,83.50726
2,0.106332,0.218182,0.418960,0.028977,0.034632,0.047969,0.448081,0.325483,0.161073,263.37860
3,0.031659,0.151515,0.281100,0.017399,0.032371,0.053789,0.210542,0.187923,0.100241,56.77525
4,0.033796,0.230303,0.278414,0.017956,0.007300,0.019674,0.181456,0.030828,0.028489,188.75957

LiDAR Data Preview:

,Status,origin,zmax,zmean,zsd,zskew,zkurt,pzabovezmean,pzabove2,zq5,...,zpcum1,zpcum2,zpcum3,zpcum4,zpcum5,zpcum6,zpcum7,zpcum8,zpcum9,Target
0,0.0,0.0,0.692364,0.421941,0.503111,0.503530,0.031636,0.287178,0.912084,0.003991,...,0.057731,0.166444,0.561836,0.715985,0.750118,0.777899,0.838672,0.904644,0.937477,1.381989
1,1.0,1.0,0.692364,0.421941,0.503111,0.503530,0.031636,0.287178,0.912084,0.003991,...,0.057731,0.166444,0.561836,0.715985,0.750118,0.777899,0.838672,0.904644,0.937477,323.132202
2,1.0,1.0,0.667812,0.517221,0.613245,0.444484,0.004845,0.550541,0.977677,0.159645,...,0.027921,0.365838,0.496470,0.505387,0.523731,0.548082,0.662059,0.820457,0.897849,353.671565
3,0.0,1.0,0.478026,0.580863,0.363620,0.314388,0.054912,0.786907,0.939859,0.038869,...,0.052749,0.083475,0.100948,0.117819,0.160610,0.249432,0.386766,0.570342,0.719632,28.793416
4,1.0,1.0,0.478026,0.580863,0.363620,0.314388,0.054912,0.786907,0.939859,0.038869,...,0.052749,0.083475,0.100948,0.117819,0.160610,0.249432,0.386766,0.570342,0.719632,253.695027

In [4]:
pip install matplotlib seaborn

Requirement already satisfied: matplotlib in c:\users\kushal\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: seaborn in c:\users\kushal\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kushal\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\kushal\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kushal\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kushal\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.23 in c:\users\kushal\anaconda3\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\kushal\anaconda3\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\kushal\anaconda3\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\kushal\anaconda3\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kushal\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\kushal\anaconda3\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\kushal\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kushal\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\kushal\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load your dataset
data = pd.read_csv('prf_I5_2000_9_norm_landsat8.csv')

# Preprocessing steps
data.fillna(method='ffill', inplace=True)  # Example: forward fill for handling missing values
data = pd.get_dummies(data)  # Convert categorical variables to dummy/indicator variables

# Split the data into training and validation sets
train_val_data, test_data = train_test_split(data, test_size=0.1, random_state=42)

C:\Users\Kushal\AppData\Local\Temp\ipykernel_11140\2740511683.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)  # Example: forward fill for handling missing values